### ISSUE TITLE
Configure the precision of the coverage badge

### ISSUE THREAD

**Issue by pquentin** [smarie/python-genbadge#16]
We're using genbadge in https://github.com/clustree/modelkit, thank you! However, changing the badge everytime the coverage changes slightly will add a lot of commit noise.

https://github.com/smarie/python-genbadge/blob/0add991840d8975b4bb43516a38c54b5537c6bb9/genbadge/utils_coverage.py#L130

Can we configure the precision as in coverage itself? https://coverage.readthedocs.io/en/coverage-5.5/config.html#report. Maybe with a `--precision` flag

**Comment by smarie** [comment]
Thanks @pquentin for the feedback !

It is not yet possible to change the precision, but it could definitely be something very easy to implement, with an additional CLI parameter to the `genbadge coverage` command. Would you feel like proposing a PR for this ?

Now on a broader topic, I personally do not commit my badges in the source: they are rather generated on the fly during the build workflow. See for example genbadge itself : the badge is generated by CI [during the "test" session](https://github.com/smarie/python-genbadge/blob/main/noxfile.py#L130)

**Comment by pquentin** [comment]
Oh, I wasn't aware of GitHub Actions artifacts, that's a much better solution, thanks!

**Comment by smarie** [comment]
You're welcome :)

That being said, I was planning some kind of common "format" option, to be discussed in #6 if you're interested !

Closing this ticket in favor of #6
