### ISSUE TITLE
Add an option to provide an alternative badge title/label or to remove it completely

### ISSUE THREAD

**Issue by smarie** [smarie/python-genbadge#17]
from #6 suggested by @achieveOrbit

Note that 

 - "label" is the name I use in the `get_svg_badge` function https://github.com/smarie/python-genbadge/blob/c973e7d5eda424363a8f8b1ae25da0aca8c4cdd9/genbadge/utils_badge.py#L93
 - "left txt" is the name I use in the `Badge` class : https://smarie.github.io/python-genbadge/#4-low-level-api

But it is not necessary to align those with the command option.

If this moves further (PRs accepted) we still need to agree on choice of option name. Unfortunately `-t` ("threshold" in the tests command) and `-l` ("local" in all commands) are already used. Of course `click` allow us to not specify a short command, we could only accept a long command. But that would be a little sad...

What about `-n/--name` ?

I'm open to suggestions here :)

**Comment by texnofobix** [comment]
`-n/--name` seems sufficient here.

**Comment by smarie** [comment]
Thanks for the feedback @texnofobix ! I'm still puzzled about the option to "remove the title completely". I hesitate between

 - implicit: `-n ""` would remove the name part of the badge entirely
 - explicit: having a second flag-type option --noname/[--withname]. In that case `-n ""` would set an empty name but not remove the left part of the badge, while setting `--noname` would remove the left part of the badge.

I have a small preference for the second one, as explicit is often better than implicit.

I'll have to take a few minutes to implement this one of these days. Except if you wish to give it a stab yourself ? Let me know, it depends how urgent/important this is for you.
