### ISSUE TITLE
error in xunitparser setup command: use_2to3 is invalid

### ISSUE THREAD

**Issue by smarie** [smarie/python-genbadge#18]
`pip install genbadge[tests]` installs the `xunitparser` dependency.

However it seems that this library can not be installed on `setuptools>=58` because `use_2to3` is not supported anymore.
(see https://stackoverflow.com/a/69100830/7262247)

I'll open an issue at `xunitparser`. But since this may be long to be fixed, I might as well remove the dependency in the meantime

**Comment by connerxyz** [comment]
I'm experiencing this same issue.

**Comment by smarie** [comment]
@connerxyz it was fixed in latest version of `genbadge`: `xunitparser` was removed from the dependencies

Note: You can use `genbadge.xunitparser_copy` as a replacement for the xunitparser module, if needed
