### ISSUE TITLE
pytest, pytest-cov command to generate report is out-of-date

### ISSUE THREAD

**Issue by sandeep-gh** [smarie/python-genbadge#27]
In the documentation (https://smarie.github.io/python-genbadge/) for pytest -- the report generation command is no longer correct: 

> pytest --junitxml=reports/junit/junit.xml --html=reports/junit/report.html

The correct statement should be something like:
```
pytest --cov --junitxml=reports/junit/junit.xml --cov-report=xml:reports/coverage/coverage.xml  --cov-report=html:reports/coverage/coverage.html 
```

**Comment by smarie** [comment]
Thanks @sandeep-gh for this information ! 

I recently ran this command on another project and it seems to work still:

https://github.com/smarie/mkdocs-gallery/actions/runs/4983044289/jobs/8919572657#step:6:53

(on Python 3.8.10, pytest-7.3.1, plugins: html-3.2.0, metadata-2.0.4)

So I guess that this is for a later version of `pytest` ?

**Comment by smarie** [comment]
@sandeep-gh : should I consider this issue closed ?

**Comment by smarie** [comment]
closing for now, feel free to reopen !
