### ISSUE TITLE
plugin flak8-html missing from the docs

### ISSUE THREAD

**Issue by sandeep-gh** [smarie/python-genbadge#28]
The docs should mention that flake8-html is required for genbadge to run.

**Comment by smarie** [comment]
Thanks @sandeep-gh  ! 

For which step exactly is it required ? Do you get an error message when you run

`flake8 <src_folder> --exit-zero --statistics --tee --output-file flake8stats.txt`

? 

As mentioned in https://smarie.github.io/python-genbadge/#prerequisite-a-flake8-report, the html part is optional.
Maybe the text of the documentation could be improved ? If so, which improvement would you suggest ? Thanks in advance !

**Comment by smarie** [comment]
@sandeep-gh : should I consider this issue closed ?

**Comment by smarie** [comment]
closing for now, feel free to reopen !
