### ISSUE TITLE
genbadge unable to read flake8 output.

### ISSUE THREAD

**Issue by sandeep-gh** [smarie/python-genbadge#29]
I have tried giving no format option, and  format=html. Both of them end up with same type of error/warning. 
Is this  is an encoding issue?. 

/home/kabiraatmonallabs/to_githubcodes/addict-tracking-changes/.nox/badges/lib/python3.11/site-packages/genbadge/utils_flake8.py:119: UserWarning: Line in Flake8 statistics report does not match template and will be ignored: '\x1b[1msrc/addict_tracking_changes/__init__.py\x1b[m\x1b[36m:\x1b[m30\x1b[36m:\x1b[m1\x1b[36m:\x1b[m \x1b[1m\x1b[31mE303\x1b[m too many blank lines (3)'

**Comment by smarie** [comment]
As mentioned in https://smarie.github.io/python-genbadge/#prerequisite-a-flake8-report

> You can redirect this to a file named flake8stats.txt using --tee --output-file flake8stats.txt. **This is the file that we'll need to generate the badge.**

This is therefore the same issue as in #28 : you probably overlooked this part of the doc ?
As for #28, I would appreciate any proposal to make the doc clearer. Maybe simply highlighting the words above in bold in the doc would make the trick ? Let me know.

**Comment by smarie** [comment]
@sandeep-gh : should I consider this issue closed ?

**Comment by smarie** [comment]
closing for now, feel free to reopen !
