### ISSUE TITLE
Issue when using Pillow 10

### ISSUE THREAD

**Issue by pg** [smarie/python-genbadge#31]
I just noticed an issue with this library when using Pillow 10: `'FreeTypeFont' object has no attribute 'getsize'`. 

I ended up downgrading to Pillow 9.5 and things worked okay. Hopefully I can help others if they hit the same error.

**Comment by smarie** [comment]
Thanks for reporting ! And thanks @famura for the tip.
Would anyone wish to propose a PR ?

**Comment by famura** [comment]
> Thanks for reporting ! And thanks @famura for the tip.
> Would anyone wish to propose a PR ? 

Hi @smarie, I already made a very small pr that should be mentioned indirectly here (linked by GitHub since I mentioned this issue in the PR). Let me know if it works for you

**Comment by smarie** [comment]
Indeed, sorry I missed this. I just approved it, let's check the results
