### ISSUE TITLE
Support Python 3.12

### ISSUE THREAD

**Issue by Timmeeh** [smarie/python-genbadge#32]
[Python 3.12](https://docs.python.org/3/whatsnew/3.12.html) no longer installs `setuptools` into virtual environments. `setuptools` is still used by _genbadge_. Please consider removing the dependency on setuptools or adding it explicitly as a requirement. Similar cases [here](https://github.com/python/cpython/issues/95299).

**Comment by smarie** [comment]
Thanks @Timmeeh . Indeed this was also reported in #34
